# Use language: c because perl builds are not available on macOS
language: c

matrix:
  include:
    - os: linux
    - os: osx

env:
  global:
    - VERBOSE=1

script:
  - autoreconf -fi && ./configure --enable-silent-rules
  - make distcheck
