[build-system]
requires = ["argparse-manpage[setuptools] @ git+https://github.com/praiskup/argparse-manpage.git"]

[tool.mypy]
exclude = [
    '^dist',
    '^build',
    '^tests-output',
]
strict = true
